# Generated by Django 3.2.2 on 2021-05-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=255)),
                ('Idade', models.IntegerField(blank=True, null=True)),
                ('Espécie', models.CharField(max_length=255)),
                ('Gênero', models.CharField(max_length=255)),
                ('Ocupação', models.CharField(max_length=255)),
                ('Descrição', models.TextField(max_length=255)),
            ],
        ),
    ]
