# Generated by Django 3.2.2 on 2021-05-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='Descrição',
            field=models.TextField(max_length=999),
        ),
    ]
