# Generated by Django 3.2.2 on 2021-06-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_personagem_descrição'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='Foto',
            field=models.ImageField(default=1, upload_to='', width_field=300),
            preserve_default=False,
        ),
    ]
