# Generated by Django 3.2.2 on 2021-06-05 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_personagem_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personagem',
            name='Foto',
        ),
    ]
